env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - standard-with-typescript
  - prettier
  - plugin:react/jsx-runtime
overrides: [ ]
parserOptions:
  project: ./tsconfig.json
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {
  react/prop-types: off,
  "@typescript-eslint/explicit-function-return-type": off,
  "@typescript-eslint/no-unused-vars": "warn",
  "@typescript-eslint/no-misused-promises": off,
  "@typescript-eslint/no-floating-promises": off,
  react/display-name: warn,
  "@typescript-eslint/strict-boolean-expressions": off
}
